{{- $releaseName := .Release.Name -}}
{{- $chartName := include "store-trigger.name" . -}}
{{- $cloudProviderFlavor := include "store-trigger.cloudProviderFlavor" . -}}
{{- $fullName := include "store-trigger.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "store-trigger.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $fullName }}
    {{- include "store-trigger.selectorLabels" . | nindent 4 }}
